name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    environment: google-cloud
    runs-on: ubuntu-latest
    outputs:
      server_image_tag: ${{ env.SERVER_IMAGE_TAG }}
      vidgen_image_tag: ${{ env.VIDGEN_IMAGE_TAG }}
    steps:      
      - name: ⚙️ Set up repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: ⚙️ Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: ⚙️ Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: 'bai-buchai-p'

      - name: 🔐 Configure Docker authentication
        run: |
          gcloud auth configure-docker us-east1-docker.pkg.dev --quiet

      - name: 🏗️ Build Docker images
        env:
          SERVER_IMAGE_TAG: us-east1-docker.pkg.dev/bai-buchai-p/bai-buchai-p-gar-usea1-docker/buch-ai-server:0.1.0
          VIDGEN_IMAGE_TAG: us-east1-docker.pkg.dev/bai-buchai-p/bai-buchai-p-gar-usea1-docker/buch-ai-video-generator:0.1.0
        run: |
          # Build server image
          docker build -t $SERVER_IMAGE_TAG --platform linux/amd64 \
            --build-arg AUTH_JWT_KEY=${{ secrets.AUTH_JWT_KEY }} \
            --build-arg HF_API_KEY=${{ secrets.HF_API_KEY }} \
            .
          
          # Build task image: Video Generator
          docker build -t $VIDGEN_IMAGE_TAG --platform linux/amd64 \
            -f app/tasks/video_generator/Dockerfile \
            .

      - name: 📤 Push Docker images
        env:
          SERVER_IMAGE_TAG: us-east1-docker.pkg.dev/bai-buchai-p/bai-buchai-p-gar-usea1-docker/buch-ai-server:0.1.0
          VIDGEN_IMAGE_TAG: us-east1-docker.pkg.dev/bai-buchai-p/bai-buchai-p-gar-usea1-docker/buch-ai-video-generator:0.1.0
        run: |
          docker push $SERVER_IMAGE_TAG
          docker push $VIDGEN_IMAGE_TAG
