name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    environment: google-cloud
    runs-on: ubuntu-latest
    steps:      
      - name: ⚙️ Set up repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: ⚙️ Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: ⚙️ Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: 'bai-buchai-p'

      - name: 🔐 Configure Docker authentication
        run: |
          gcloud auth configure-docker us-east1-docker.pkg.dev --quiet

      - name: 🏗️ Build Docker images
        env:
          SERVER_IMAGE_TAG: us-east1-docker.pkg.dev/bai-buchai-p/bai-buchai-p-gar-usea1-docker/buch-ai-server:0.1.0
          TASK_VG_IMAGE_TAG: us-east1-docker.pkg.dev/bai-buchai-p/bai-buchai-p-gar-usea1-docker/buch-ai-video-generator:0.1.0
        run: |
          # Build server image
          docker build -t $SERVER_IMAGE_TAG --platform linux/amd64 \
            --build-arg AUTH_JWT_KEY=${{ secrets.AUTH_JWT_KEY }} \
            --build-arg HF_API_KEY=${{ secrets.HF_API_KEY }} \
            .
          
          # Build task image: Video Generator
          docker build -t $TASK_VG_IMAGE_TAG --platform linux/amd64 \
            -f app/tasks/video_generator/Dockerfile \
            .

      - name: 📤 Push Docker images
        env:
          SERVER_IMAGE_TAG: us-east1-docker.pkg.dev/bai-buchai-p/bai-buchai-p-gar-usea1-docker/buch-ai-server:0.1.0
          TASK_VG_IMAGE_TAG: us-east1-docker.pkg.dev/bai-buchai-p/bai-buchai-p-gar-usea1-docker/buch-ai-video-generator:0.1.0
        run: |
          docker push $SERVER_IMAGE_TAG
          docker push $TASK_VG_IMAGE_TAG
    outputs:
      server_image_tag: us-east1-docker.pkg.dev/bai-buchai-p/bai-buchai-p-gar-usea1-docker/buch-ai-server:0.1.0
      video_gen_image_tag: us-east1-docker.pkg.dev/bai-buchai-p/bai-buchai-p-gar-usea1-docker/buch-ai-video-generator:0.1.0

  deploy:
    needs: build
    environment: google-cloud
    runs-on: ubuntu-latest
    steps:
      - name: ⚙️ Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: ⚙️ Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: 'bai-buchai-p'

      - name: 🚀 Deploy to Cloud Run
        run: |
          # Deploy server
          gcloud run deploy bai-buchai-p-run-usea1-server \
            --region us-east1 \
            --image ${{ needs.build.outputs.server_image_tag }} \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars "AUTH_JWT_KEY=${{ secrets.AUTH_JWT_KEY }}" \
            --set-env-vars "HF_API_KEY=${{ secrets.HF_API_KEY }}"
          
          # Deploy task: Video Generator
          gcloud run jobs update buch-ai-video-generator \
            --image ${{ needs.build.outputs.video_gen_image_tag }} \
            --region us-east1 \
            --memory 2Gi \
            --cpu 2 \
            --max-retries 2 \
            --task-timeout 30m \
            || gcloud run jobs create buch-ai-video-generator \
               --image ${{ needs.build.outputs.video_gen_image_tag }} \
               --region us-east1 \
               --memory 2Gi \
               --cpu 2 \
               --max-retries 2 \
               --task-timeout 30m
